


# -*- coding: utf-8 -*-
"""Copy of PythonLab CO1 & CO2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e4Al4AhNGoCflRWcf8aLbzDPaL7KI-Vn
"""

#if sataement
age=int(input("enter you age"))
if(age>=18):
  print(" you are eligible")
print("Now i am out of if")
print("..............")

#if else staement ...even /odd checking
n=int(input("enter the number"))
if(n%2==0):
  print("even number")
else:                                                                                                                                                     
    print("odd number")
print("..............")

#if elif else staement ...Grade of a student
mark=int(input("enter your mark"))
if(mark>=90):
  print("Grade A")
elif(mark<=89 and mark>70):
  print("Grade B")
elif(mark<=69 and mark>=50):
  print("Grade C")
else:
  print("Fail")
print("..............")

#Nested if
x=int(input("enter no1: "))
y=int(input("enter no2: "))
z=int(input("enter no3: "))
if  x>y:
	if x>z:
		print("largest is",x)
	else:
		print("largest is",z)
else:
	if y>z:
		print("largest is",y)
	else:
		print("largest is",z)

"""**break and continue,pass**"""

name=input("enter your name")
for i in name:
  if(i=="a"):
    break
  print(i)
print(".................")
for i in "sreelatha":
  if(i=="e"):
    continue
  print(i,end=" ")
print("\n.................")
seq=['s','a','d']
for v in seq:
  pass

"""**Loop**"""

c=1
while(c<=10):
      print(c,end=" ")
      c=c+1
print("\n.................")
for c in range(1,11):
  print(c,end=" ")
for i in "123":
  print('welcome',i,'times')
else:
  print("out of loop")
print("\n.................")
#while else
x,s=0,0
while(x<10):
    s=s+x
    x=x+1
else:
  print("The sum of 1st 9 integers is:",s)

"""**Nested Loops**"""

n=2
i=0
while (i<=2):
  j=0
   
  while(j<=2):
    print(n,end=" ")
    j=j+1
  i=i+1   
  print()
print("................")
n=2
for i in range( 0,3):

  for j in range(0,3):

    print(n,end =" ")
  print()

"""**Traversing through string using while and for**"""

str="Computer science"
for i in str:
  print(i,end=" ")
print("\n...............")
index=0
while(index<len(str)):
  print(str[index],end=" ")
  index=index+1

"""**Reversing a String**"""

str=input("enter a string:")
for i in range(-1,-len(str)-1,-1):
  print(str[i],end="")

"""**find and replace a substring in a given string**"""

ostring=input("Enter the root string:")
sstring=input("Enter the  substring to be searched:")

#f=ostring.find(sstring)
#print(f,"\n")
if(ostring.find(sstring)>0):
  print(sstring,":found\n")
  rstring=input("Enter the new string to be replaced with:")
  print("the root string after replacing:")
  print(ostring.replace(sstring,rstring))
else:
  print(sstring,":not found\n")

#print(ostring)

"""**Loop in List** ---count how many times a substring occur in a line and displays the count"""

ostring=input("Enter the line:")
sstring=input("Enter the substring:")
lst=ostring.split()
count=0
for i in lst:
  if(i==sstring):
    count=count+1

print(sstring,"appears in ",ostring,count,"times")

"""**Find the common element among the two inputted lists**"""

l1=[1,100,200,4,5,600]
l2=[2,10,100,4,500]
for x in l1:
  for y in l2:
    if(x==y):
      print("The common element is:",x)

"""**Name sorting using sort() and sorted()**"""

n=int(input("entre the number of strings:"))
ln=[]
for i in range(0,n):
  name=input("enter name:")
  ln.append(name)
ls=ln.sort()
print("The name sorting using sorted():",sorted(ln))
print("The name sorting using sort():")
ln.sort(reverse=True)
print(ln)

"""Delete -ve and odd numbers from a list of numbers

"""

ln=[]
for i in range(1,6):
  n=int(input("enter number:"))
  ln.append(n)
c=len(ln)
i=0
while(i<len(ln)):
  if(ln[i]<0):
    del ln[i]
    i=i-1
    c=c-1
  elif(ln[i]%2!=0):
    del ln[i]
    i=i-1
    c=c-1
  i=i+1
print("list after deletion:",ln)

"""**Dictionary**"""

stud={"regno":250,"age":21,"mark":45}
print(stud)
print(stud["age"])
stud['age']=22      #changing value of a key
print(stud['age'])
stud['Name']="Teena"      # adding new key and value
print(stud)

place={'location':'perunna','dist':'EKM','pin':658934}
del place['pin']      # deleting an element
print(place)
place.clear();        # clearing the contents
print(place)

"""**Function**"""

def sum(a,b):
  "adding two values"
  s=a+b
  print("sum is",s)
  
sum(10,20)

def prints(N=5):                      # default argument
	for i in range(1,N+1):
		print(i)
	return
prints()

sum=lambda x,y,z:x+y+z                # lamda function 
print("total=",sum(2,3,5))

oldlist=[3,9,34,56,23]                # lamda in filter function
newlist=list(filter(lambda x:x%2==0,oldlist))
print("oldlist ",oldlist)
print("newlist ",newlist)


oldlist=[3,9,34,56,23]                # lamda in map function
newlist=list(map(lambda x:x*2,oldlist))
print("oldlist ",oldlist)
print("newlist ",newlist)

def calc_factorial(x):                # Recursive function

	if x == 1:
       
		 return 1
 
	else:
		return (x * calc_factorial(x-1))

num = int(input("Enter a number to find factorial"))
print("The factorial of", num, "is", calc_factorial(num))	

print("Arithmetic Calculation" ) 
def calc(a,b):                                  #  Returning morethan one values
	sum=a+b
	diff=a-b
	prod=a*b
	quo=a/b
	return sum,diff,prod,quo;

a=int(input("Enter first number:"))
b=int(input("Enter1 second number:"))
s,d,p,q=calc(a,b)
print("sum=",s)
print("diff=",d)
print("prod=",p)
print("quotient=",q)